name = "your-p13n-worker"
main = "src/index.ts"
account_id = "f39f700e75c45960a1b4e1ad200acd82"
route = ""
workers_dev = true
compatibility_date = "2023-10-23"

[vars]
ORIGIN_URL = "https://yoursloworigin.com"